name: pyladies-amsterdam-etl

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - NumPy
  - SciPy
  - matplotlib
  - seaborn
  - pandas
  - Sphinx
  - requests
  - google-api-core
  - google-cloud-bigquery
  - google-cloud-storage
  - pip
  - pip:
    - -rgithubrequirements.txt

