apiVersion: v1
kind: ConfigMap
metadata:
  name: pyladies-amsterdam-etl-config-prod
  namespace: pyladies-amsterdam-etl
data:
  SOURCES: "source-1 source-2"
  # DTAP Environment
  ENVIRONMENT: "prod"
  # GCP project and bucket for input raw data
  RAW_DATA_PROJECT_GCP_KEY: "/src/keys/gcp_raw_data_key.json"
  RAW_DATA_PROJECT_GCP: "nimellaa-prod"
  RAW_DATA_BUCKET_GCP: "pyladies-amsterdam-etl-data-prod"
  # GCP project and bucket to upload log files
  LOG_FILES_PROJECT_GCP_KEY: "/src/keys/gcp_storage_key.json"
  LOG_FILES_PROJECT_GCP: "nimellaa-prod"
  LOG_FILES_BUCKET: "pyladies-amsterdam-etl-logs-prod"
  LOG_FILES_PATH: "/src/logs"
  # GCP project for this repository
  GOOGLE_CLOUD_PROJECT_KEY: "/src/keys/gcp_bigquery_key.json"
  GOOGLE_CLOUD_PROJECT: "nimellaa-prod"
  # Client specific settings
  SCRIPTS_DIR: "/src/models"
  DATASET_BIG_QUERY: "{}_DATASET_BIG_QUERY"
  SCRIPTS: "{}_SCRIPTS"
  # Source 1 Settings
  # Source 2 BigQuery dataset name
  SOURCE-1_DATASET_BIG_QUERY: "source_1"
  # List of files to process
  SOURCE-1_SCRIPTS: "source1"
  # Source 2 Settings
  # Source 2 BigQuery dataset name
  SOURCE-2_DATASET_BIG_QUERY: "source_2"
  # List of files to process
  SOURCE-2_SCRIPTS: "source2a source2b"